# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-24 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=6)),
                ('c_stu_nums', models.IntegerField()),
                ('c_intro', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'class',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=6)),
                ('stu_sex', models.BooleanField(default=0)),
                ('stu_birth', models.DateField()),
                ('stu_tel', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
