# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 02:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0002_student_stu_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='g',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stu.Class'),
        ),
    ]
