# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0003_student_g'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_addr', models.CharField(max_length=15)),
                ('sinfo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='stu.Student')),
            ],
            options={
                'db_table': 'stu_info',
            },
        ),
    ]
